name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: check files
        run: |
          ls -la
          tree .

      - name: args setup
        run: |
          echo "PROJECT_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "TAG_NAME=$(basename ${{ github.ref }})" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(basename ${{ github.repository }})-$(basename ${{ github.ref }})" >> $GITHUB_ENV

      - name: Display environment variables
        run: |
          echo "Project Name: $PROJECT_NAME"
          echo "Tag Name: $TAG_NAME"
          echo "Release Name: $RELEASE_NAME"

      - name: create temporary workspace
        run: |
          mkdir -p temp
          mv dir temp/
          mv a temp/
          mv b temp/

      - name: Create release archive
        run: |
          cd temp/
          zip -r $RELEASE_NAME.zip * 
          mkdir _temp_release_assets
          mv $RELEASE_NAME.zip ./_temp_release_assets/
          cd ..

      - name: check files
        run: |
          ls -la
          tree .

      - name: Upload Release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./temp/_temp_release_assets/${{ env.RELEASE_NAME }}.zip

